# Generated by Django 5.0.1 on 2024-01-23 17:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoftDeskAPI', '0004_remove_project_contributors_contributor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='issue_contrib',
        ),
        migrations.AddField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(related_name='projects', through='SoftDeskAPI.Contributor', to=settings.AUTH_USER_MODEL),
        ),
    ]
